taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/dylanhill/Documents/3rdYear/DS_Engineering/ds3022-data-project-1/emissions.duckdb'
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
